In [40]:
import pandas as pd

In [41]:
file_path = r"C:\Users\deven\Downloads\distance_BoM_to_generators.xlsx"

In [42]:
df = pd.read_excel(file_path, skiprows=5)  # Skip header rows

In [43]:
df.head()

,Bureau of Meteorology Station Number,Latitude to 4 decimal places (in decimal degrees),Longitude to 4 decimal places (in decimal degrees),State,BANGOWF1,BANGOWF2,BOCORWF1,BODWF1,CAPTL_WF,COLWF01,...,CSPVPS1,HAMISF1,WHITSF1,HAYMSF1,DAYDSF1,CLARESF1,HAUGHT11,RRSF1,SMCSF1,KSP1
0,109504,-33.8707,121.8971,WA,2473.769073,2466.852814,2481.475840,2527.184809,2525.316368,2517.836563,...,2947.088073,2944.705035,2944.214977,2945.907368,2947.386720,2942.759406,2935.754163,2930.380116,2949.982200,2761.247992
1,109521,-34.0258,115.0637,WA,3091.207427,3084.459230,3086.136953,3153.392381,3139.407982,3133.522820,...,3545.440847,3542.681769,3542.043798,3543.783465,3545.213247,3534.390327,3526.132123,3517.120054,3536.827393,3330.237097
2,140007,-27.5433,153.2394,QLD,886.628313,887.865649,1078.445126,673.543651,915.322614,892.061506,...,953.891491,959.757497,962.051141,961.305807,962.062922,1053.719263,1071.250823,1120.743123,1119.837353,1336.896153
3,140008,-28.0437,153.1871,QLD,834.926378,836.352957,1024.522956,625.980258,861.918233,839.089474,...,996.281046,1002.048551,1004.320300,1003.639295,1004.450253,1095.761147,1113.013836,1162.214159,1161.952546,1372.613438
4,140009,-27.6932,152.9935,QLD,860.908756,862.022615,1054.588621,645.942682,890.961158,867.306239,...,953.377418,959.162849,961.438720,960.746250,961.547836,1052.929620,1070.236636,1119.498840,1119.113015,1331.434018

In [44]:
import numpy as np

def find_closest_bureau(df):
    result_df = pd.DataFrame()
    
    # Extract the basic information
    result_df['ID'] = df.iloc[:, 0]
    result_df['Latitude'] = df.iloc[:, 1]
    result_df['Longitude'] = df.iloc[:, 2]
    result_df['State'] = df.iloc[:, 3]
    
    # Get distances and generators names (all columns from column 5 onwards)
    distance_df = df.iloc[:, 4:]
    
    # Find the minimum distance and corresponding bureau for each row
    result_df['Generator'] = distance_df.idxmin(axis=1)
    result_df['Distance'] = distance_df.min(axis=1)
    
    return result_df

In [45]:
result = find_closest_bureau(df)

# Display the results
print(result)

          ID  Latitude  Longitude State Generator     Distance
0     109504  -33.8707   121.8971   WA   CATHROCK  1260.328239
1     109521  -34.0258   115.0637   WA   CATHROCK  1880.994906
2     140007  -27.5433   153.2394   QLD   WARWSF2   134.691898
3     140008  -28.0437   153.1871   QLD   WARWSF2   110.183685
4     140009  -27.6932   152.9935   QLD   WARWSF2   105.321789
...      ...       ...        ...   ...       ...          ...
1587   98018  -39.9333   143.8667   TAS  WOOLNTH1   116.172132
1588   99001  -39.4764   147.3153   TAS   TOORAWF   124.666869
1589   99005  -40.0911   148.0024   TAS  MUSSELR1    76.778786
1590   99015  -40.1214   148.0167   TAS  MUSSELR1    73.386139
1591   99022  -40.2028   148.2372   TAS  MUSSELR1    66.733249

[1592 rows x 6 columns]

In [46]:
import pandas as pd
import numpy as np

def find_closest_ids(df):
    """
    Analyze a dataframe to find the closest ID for each generator based on distance.
    
    Parameters:
    df (pandas.DataFrame): DataFrame with first 4 columns as 'ID', 'latitude', 'longitude', 'state',
                          and remaining columns are generator names with distance values
    
    Returns:
    pandas.DataFrame: A table with generator names, closest ID, and the distance
    """
    result_df = pd.DataFrame()
    
    # Extract the basic information
    result_df['ID'] = df.iloc[:, 0]
    result_df['Latitude'] = df.iloc[:, 1]
    result_df['Longitude'] = df.iloc[:, 2]
    result_df['State'] = df.iloc[:, 3]
    
    # Get distances and generators names (all columns from column 5 onwards)
    distance_df = df.iloc[:, 4:]
    
    # Create empty lists to store results
    generators = []
    closest_ids = []
    min_distances = []
    closest_latitudes = []
    closest_longitudes = []
    closest_states = []
    
    # For each generator column
    for generator in distance_df.columns:
        # Find the index of the minimum distance for this generator
        min_idx = distance_df[generator].idxmin()
        
        # Get the minimum distance
        min_distance = distance_df.loc[min_idx, generator]
        
        # Add to our lists
        generators.append(generator)
        closest_ids.append(df.iloc[min_idx, 0])  # ID
        min_distances.append(min_distance)
        closest_latitudes.append(df.iloc[min_idx, 1])  # Latitude
        closest_longitudes.append(df.iloc[min_idx, 2])  # Longitude
        closest_states.append(df.iloc[min_idx, 3])  # State
    
    # Create the final result dataframe
    final_result = pd.DataFrame({
        'Generator': generators,
        'Closest_ID': closest_ids,
        'Distance': min_distances,
        'Latitude': closest_latitudes,
        'Longitude': closest_longitudes,
        'State': closest_states
    })
    
    return final_result

# Example usage:
# Assuming df is your dataframe with the first 4 columns as ID, latitude, longitude, state
# and the rest of the columns are generator names with distance values
result = find_closest_ids(df)
print(result)

    Generator  Closest_ID   Distance  Latitude  Longitude State
0    BANGOWF1       73138  68.444311  -34.2493   148.2475   NSW
1    BANGOWF2       73138  60.968217  -34.2493   148.2475   NSW
2    BOCORWF1       70217  35.126051  -36.2939   148.9725   NSW
3      BODWF1       65012  46.170122  -32.2385   148.6089   NSW
4    CAPTL_WF       70014  33.265327  -35.3049   149.2014   NSW
..        ...         ...        ...       ...        ...   ...
194  CLARESF1       33002  30.583864  -19.6169   147.3758   QLD
195  HAUGHT11       33002  37.394616  -19.6169   147.3758   QLD
196     RRSF1       32195   5.278857  -19.4082   146.7620   QLD
197    SMCSF1       32195  14.540348  -19.4082   146.7620   QLD
198      KSP1       30036  84.582032  -18.1472   144.3183   QLD

[199 rows x 6 columns]

In [47]:
from nemosis import static_table

In [48]:
raw_data_cache = r'D:\NEM_cache'
dispatch_units = static_table(table_name='Generators and Scheduled Loads', 
                              raw_data_location=raw_data_cache)

INFO: Retrieving static table Generators and Scheduled Loads
WARNING: {'Reg Cap (MW)'} not in D:\NEM_cache\NEM Registration and Exemption List.xls. Loading ['Participant', 'Station Name', 'Region', 'Dispatch Type', 'Category', 'Classification', 'Fuel Source - Primary', 'Fuel Source - Descriptor', 'Technology Type - Primary', 'Technology Type - Descriptor', 'Aggregation', 'DUID']

In [49]:
gen_df = pd.DataFrame(dispatch_units)

In [50]:
solar_duids = gen_df.loc[gen_df["Fuel Source - Primary"] == "Solar", "DUID"].tolist()
print(solar_duids)

['ADPPV1', 'ADPPV2', 'ADPPV3', 'AVLSF1', 'BAKING1', 'BANN1', 'BARCSF1', 'BERYLSF1', 'BLUEGSF1', 'BOWWPV1', 'BOMENSF1', 'BROKENH1', 'BNGSF1', 'BNGSF2', 'CESF1', 'CHILDSF1', 'CBWWPV1', 'CBWWPV2', 'CLARESF1', 'CLERMSF1', 'COHUNSF1', 'COLEASF1', 'CSPVPS1', 'COLUMSF1', 'CRWASF1', 'DDSF1', 'DARLSF1', 'DAYDSF1', 'EDENVSF1', 'EMERASF1', 'FINLYSF1', 'GANGARR1', 'GANNSF1', 'GIRGSF', 'GLENSF1', 'GLRWNSF1', 'GOONSF1', 'GRIFSF1', 'GULLRSF1', 'GNNDHSF1', 'HAMISF1', 'HVWWPV1', 'HAUGHT11', 'HAYMSF1', 'HILLSTN1', 'HUGSF1', 'JEMALNG1', 'JUNEESF1', 'KARSF1', 'KEPSF1', 'KERNGSP1', 'KIAMSF1', 'KSP1', 'KINGASF1', 'LILYSF1', 'LIMOSF11', 'LIMOSF21', 'LRSF1', 'MANSLR1', 'MAPS2PV1', 'MAPS3PV1', 'MANNSF2', 'MARYRSF1', 'METZSF1', 'MIDDLSF1', 'MOKOSF1', 'MOLNGSF1', 'MOREESF1', 'MWPS1PV1', 'MWPS2PV1', 'MWPS3PV1', 'MWPS4PV1', 'MOUSF1', 'MLSP1', 'MBPS2PV1', 'NASF1', 'NEVERSF1', 'NEWENSF1', 'NEWENSF2', 'NUMURSF1', 'NYNGAN1', 'OAKEY1SF', 'OAKEY2SF', 'PARSF1', 'PAREPS1', 'RRSF1', 'ROYALLA1', 'RUGBYR1', 'SEBSF1', 'SKSF1', 'STUBSF1', 'STUBSF2', 'SMCSF1', 'SUNRSF1', 'SUNTPSF1', 'SRSF1', 'TB2SF1', 'TBSF1', 'VALDORA1', 'WAGGNSF1', 'WLWLSF1', 'WLWLSF2', 'WANDSF1', 'WARWSF1', 'WARWSF2', 'WELNSF1', 'WELLSF1', 'WEMENSF1', 'WSTWYSF1', 'WDGPH1', 'WRSF1', 'WHITSF1', 'WINTSF1', 'WOLARSF1', 'WOOLGSF1', 'WUNUSF1', 'WYASF1', 'YARANSF1', 'YATSF1']

In [51]:
def check_solar_duids_in_results(solar_duids, result_df):
    """
    Check if each name in solar_duids list is present in the results dataframe.
    
    Parameters:
    solar_duids (list): List of solar generator names
    result_df (pandas.DataFrame): Result from find_closest_ids function
    
    Returns:
    pandas.DataFrame: DataFrame showing whether each solar DUID is in the results
    """
    # Create a dictionary to store results
    results = {
        'Solar_DUID': [],
        'In_Results': [],
        'Closest_ID': [],
        'Distance': []
    }
    
    # Check each solar DUID
    for duid in solar_duids:
        # Check if this DUID is in the Generator column of result_df
        if duid in result_df['Generator'].values:
            # Get the row for this generator
            row = result_df[result_df['Generator'] == duid].iloc[0]
            
            results['Solar_DUID'].append(duid)
            results['In_Results'].append(True)
            results['Closest_ID'].append(row['Closest_ID'])
            results['Distance'].append(row['Distance'])
        else:
            results['Solar_DUID'].append(duid)
            results['In_Results'].append(False)
            results['Closest_ID'].append(None)
            results['Distance'].append(None)
    
    # Create DataFrame from results
    check_df = pd.DataFrame(results)
    
    # Summary statistics
    total_duids = len(solar_duids)
    duids_in_results = check_df['In_Results'].sum()
    duids_not_in_results = total_duids - duids_in_results
    
    print(f"Total solar DUIDs: {total_duids}")
    print(f"DUIDs found in results: {duids_in_results} ({duids_in_results/total_duids*100:.1f}%)")
    print(f"DUIDs not found in results: {duids_not_in_results} ({duids_not_in_results/total_duids*100:.1f}%)")
    
    return check_df

# Example usage in your notebook:
# Assuming you've already run find_closest_ids and have the result in 'result_df'
check_result = check_solar_duids_in_results(solar_duids, result)
display(check_result)

Total solar DUIDs: 119
DUIDs found in results: 104 (87.4%)
DUIDs not found in results: 15 (12.6%)

    Solar_DUID  In_Results  Closest_ID   Distance
0       ADPPV1        True     23885.0   6.972997
1       ADPPV2        True     23885.0   7.224201
2       ADPPV3        True     23885.0   7.130475
3       AVLSF1        True     74082.0  18.642372
4      BAKING1        True     42023.0  37.369220
..         ...         ...         ...        ...
114   WOOLGSF1        True     40093.0  23.483259
115    WUNUSF1       False         NaN        NaN
116     WYASF1        True     50017.0  12.391211
117   YARANSF1        True     41359.0  39.721306
118     YATSF1        True     76031.0  19.565359

[119 rows x 4 columns]

In [52]:
wind_duids = gen_df.loc[gen_df["Fuel Source - Primary"] == "Wind", "DUID"].tolist()
print(wind_duids)

['ARWF1', 'BALDHWF1', 'BANGOWF1', 'BANGOWF2', 'BRYB2WF2', 'BRYB1WF1', 'BOCORWF1', 'BODWF1', 'BULGANA1', 'CNUNDAWF', 'CAPTL_WF', 'CATHROCK', 'CTHLWF1', 'CHALLHWF', 'CHPSTWF1', 'CHYTWF1', 'CLRKCWF1', 'CLEMGPWF', 'CODRNGTON', 'COLWF01', 'CBWF1', 'COOPGWF1', 'CROOKWF2', 'CROOKWF3', 'CROWLWF1', 'CRURWF1', 'CULLRGWF', 'DIAPURWF1', 'DULAWF1', 'DUNDWF1', 'DUNDWF2', 'DUNDWF3', 'ELAINWF1', 'FNWF1', 'FSWF1', 'FLYCRKWF', 'GPWFEST1', 'GPWFEST2', 'GPWFEST3', 'GSWF1A', 'GSWF1B1', 'GRANWF1', 'GULLRWF1', 'GULLRWF2', 'GUNNING1', 'HALLWF1', 'HALLWF2', 'HD1WF1', 'HEPWIND1', 'HDWF1', 'HDWF2', 'HDWF3', 'KABANWF1', 'KEPWF1', 'KIATAWF1', 'LKBONNY2', 'LKBONNY3', 'LKBONNY1', 'LGAPWF1', 'LGAPWF2', 'MACARTH1', 'MCINTYR1', 'MAROOWF1', 'MOORAWF1', 'MRTLSWF1', 'MLWF1', 'MEWF1', 'MTGELWF1', 'MERCER01', 'MTMILLAR', 'MUWAWF1', 'MUWAWF2', 'MUSSELR1', 'NBHWF1', 'OAKLAND1', 'PAREPW1', 'RYANCWF1', 'RYEPARK1', 'SALTCRK1', 'SAPHWF1', 'STWF1', 'SNOWSTH1', 'SNOWNTH1', 'SNOWTWN1', 'STARHLWF', 'STOCKYD1', 'TARALGA1', 'BLUFF1', 'TIMWEST', 'TOORAWF', 'WATERLWF', 'WPWF', 'WAUBRAWF', 'WRWF1', 'WGWF1', 'WHILL1', 'WONWP', 'WOODLWN1', 'WOOLNTH1', 'YSWF1', 'YAMBUKWF', 'YAWWF1', 'YENDWF1']

In [53]:
def check_solar_duids_in_results(wind_duids, result_df):
    """
    Check if each name in solar_duids list is present in the results dataframe.
    
    Parameters:
    solar_duids (list): List of solar generator names
    result_df (pandas.DataFrame): Result from find_closest_ids function
    
    Returns:
    pandas.DataFrame: DataFrame showing whether each solar DUID is in the results
    """
    # Create a dictionary to store results
    results = {
        'Wind_DUID': [],
        'In_Results': [],
        'Closest_ID': [],
        'Distance': []
    }
    
    # Check each solar DUID
    for duid in wind_duids:
        # Check if this DUID is in the Generator column of result_df
        if duid in result_df['Generator'].values:
            # Get the row for this generator
            row = result_df[result_df['Generator'] == duid].iloc[0]
            
            results['Wind_DUID'].append(duid)
            results['In_Results'].append(True)
            results['Closest_ID'].append(row['Closest_ID'])
            results['Distance'].append(row['Distance'])
        else:
            results['Wind_DUID'].append(duid)
            results['In_Results'].append(False)
            results['Closest_ID'].append(None)
            results['Distance'].append(None)
    
    # Create DataFrame from results
    check_df = pd.DataFrame(results)
    
    # Summary statistics
    total_duids = len(wind_duids)
    duids_in_results = check_df['In_Results'].sum()
    duids_not_in_results = total_duids - duids_in_results
    
    print(f"Total wind DUIDs: {total_duids}")
    print(f"DUIDs found in results: {duids_in_results} ({duids_in_results/total_duids*100:.1f}%)")
    print(f"DUIDs not found in results: {duids_not_in_results} ({duids_not_in_results/total_duids*100:.1f}%)")
    
    return check_df

# Example usage in your notebook:
# Assuming you've already run find_closest_ids and have the result in 'result_df'
wind_check_result = check_solar_duids_in_results(wind_duids, result)
display(wind_check_result)

Total wind DUIDs: 103
DUIDs found in results: 94 (91.3%)
DUIDs not found in results: 9 (8.7%)

    Wind_DUID  In_Results  Closest_ID   Distance
0       ARWF1        True     89085.0   8.063782
1    BALDHWF1        True     85099.0  19.196773
2    BANGOWF1        True     73138.0  68.444311
3    BANGOWF2        True     73138.0  60.968217
4    BRYB2WF2        True     89018.0  13.896781
..        ...         ...         ...        ...
98   WOOLNTH1        True     91245.0   8.264643
99      YSWF1        True     87021.0  11.555855
100  YAMBUKWF        True     90175.0  21.690097
101    YAWWF1        True     79040.0  17.719132
102   YENDWF1        True     87005.0  15.691323

[103 rows x 4 columns]

In [54]:
if wind_check_result is not None and not wind_check_result.empty:
    wind_check_result.to_excel(writer, sheet_name='Wind_Gen', index=False)
else:
    print("Warning: wind_check_result is empty or undefined.")

In [55]:
# Assuming you have both DataFrames ready:
# check_result (solar) and wind_check_result (wind)

output_filename = "Generation_Checks.xlsx"

with pd.ExcelWriter(output_filename, engine='openpyxl') as writer:
    check_result.to_excel(writer, sheet_name='Solar_Gen', index=False)
    wind_check_result.to_excel(writer, sheet_name='Wind_Gen', index=False)

print(f"Saved solar and wind results to '{output_filename}' in sheets 'Solar_Gen' and 'Wind_Gen'")

Saved solar and wind results to 'Generation_Checks.xlsx' in sheets 'Solar_Gen' and 'Wind_Gen'

In [56]:
pip install --upgrade openpyxl

Requirement already satisfied: openpyxl in c:\users\deven\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\deven\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [57]:
import pandas as pd

# Assuming check_result and wind_check_result are defined DataFrames
output_filename = "Generation_Checks.xlsx"

with pd.ExcelWriter(output_filename, engine='openpyxl') as writer:
    if check_result is not None and not check_result.empty:
        check_result.to_excel(writer, sheet_name='Solar_Gen', index=False)
    else:
        print("Warning: check_result is empty or undefined.")
    
    if wind_check_result is not None and not wind_check_result.empty:
        wind_check_result.to_excel(writer, sheet_name='Wind_Gen', index=False)
    else:
        print("Warning: wind_check_result is empty or undefined.")

print(f"Saved solar and wind results to '{output_filename}' in sheets 'Solar_Gen' and 'Wind_Gen'")

Saved solar and wind results to 'Generation_Checks.xlsx' in sheets 'Solar_Gen' and 'Wind_Gen'